site_name: Factor.io Docs
theme: yeti
pages:
- [index.md, Getting Started]
- [workflows.md, Defining workflows]
- [build_custom_connectors.md, Build custom connectors]
- [examples.md, Examples]
- [production.md, Run in production]
