site_name: Factor.io Docs
site_url: http://docs.factor.io/
site_author: Factor.io
theme_dir: theme
repo_url: https://github.com/factor-io/docs/
pages:
- ['index.md', 'Getting Started']
- ['index.md', 'Learn Factor.io', 'Before you start']
- ['index.md', 'Learn Factor.io', 'Your first workflow']
- ['index.md', 'Learn Factor.io', 'Adding logging to your workflow']
- ['index.md', 'Learn Factor.io', 'Calling a service']
- ['index.md', 'Learn Factor.io', 'Getting more services']
- ['index.md', 'Learn Factor.io', 'Handling failures']
- ['index.md', 'Learn Factor.io', 'Run your own connector service']
- ['index.md', 'Factor.io Pro', 'Overview']
- ['index.md', 'Factor.io Pro', 'Creating and running Workflows']
- ['index.md', 'Factor.io Pro', 'Setting Credentials']
- ['index.md', 'Factor.io Pro', 'Managing Connectors']
- ['index.md', 'Factor.io Pro', 'Membership management']
- ['index.md', 'Factor.io Pro', 'Managing Jumpstarts']
- ['connectors/bitballoon.md', 'Connectors', 'Bitballoon']
- ['connectors/github.md', 'Connectors', 'Github']
- ['connectors/heroku.md', 'Connectors', 'Heroku']
- ['connectors/hipchat.md', 'Connectors', 'Hipchat']
- ['connectors/pushover.md', 'Connectors', 'Pushover']
- ['connectors/ssh.md', 'Connectors', 'SSH']
- ['connectors/timer.md', 'Connectors', 'Timer']
- ['connectors/travis.md', 'Connectors', 'Travis']
- ['connectors/web.md', 'Connectors', 'Web']
- ['guides/self_host.md', 'Guides', 'Self hosting']
- ['guides/build_custom_connectors.md', 'Guides', 'Build custom connectors']
- ['guides/workflows.md', 'Guides', 'Defining workflows']
- ['guides/examples.md', 'Guides', 'Workflow Examples']