site_name: Factor.io Docs
site_url: http://docs.factor.io/
site_author: Factor.io
theme_dir: theme
repo_url: https://github.com/factor-io/docs/
pages:
- [index.md, Getting Started]
- [workflows.md, Defining workflows]
- [examples.md, Examples]
- [connectors.md, Connectors]
- [self_host.md, Self hosting]
- [build_custom_connectors.md, Build custom connectors]
