site_name: Factor.io Docs
site_url: http://docs.factor.io/
site_author: Factor.io
theme_dir: theme
repo_url: https://github.com/factor-io/docs/
pages:
- ['index.md', 'Getting Started']
- ['learn/step_1_before_you_start.md', 'Learn Factor.io', 'Before you start']
- ['learn/step_2_your_first_workflow.md', 'Learn Factor.io', 'Your first workflow']
- ['learn/step_3_add_logging.md', 'Learn Factor.io', 'Adding logging to your workflow']
- ['learn/step_4_calling_a_service.md', 'Learn Factor.io', 'Calling a service']
- ['learn/step_5_getting_more_services.md', 'Learn Factor.io', 'Getting more services']
- ['learn/step_6_handling_failures.md', 'Learn Factor.io', 'Handling failures']
- ['learn/step_7_run_your_own_connector.md', 'Learn Factor.io', 'Run your own connector service']
- ['index.md', 'Factor.io Pro', 'Overview']
- ['index.md', 'Factor.io Pro', 'Creating and running Workflows']
- ['index.md', 'Factor.io Pro', 'Setting Credentials']
- ['index.md', 'Factor.io Pro', 'Managing Connectors']
- ['index.md', 'Factor.io Pro', 'Membership management']
- ['index.md', 'Factor.io Pro', 'Managing Jumpstarts']
- ['connectors/bitballoon.md', 'Connectors', 'Bitballoon']
- ['connectors/github.md', 'Connectors', 'Github']
- ['connectors/heroku.md', 'Connectors', 'Heroku']
- ['connectors/hipchat.md', 'Connectors', 'Hipchat']
- ['connectors/pushover.md', 'Connectors', 'Pushover']
- ['connectors/ssh.md', 'Connectors', 'SSH']
- ['connectors/timer.md', 'Connectors', 'Timer']
- ['connectors/travis.md', 'Connectors', 'Travis']
- ['connectors/web.md', 'Connectors', 'Web']
- ['guides/self_host.md', 'Guides', 'Self hosting']
- ['guides/build_custom_connectors.md', 'Guides', 'Build custom connectors']
- ['guides/workflows.md', 'Guides', 'Defining workflows']
- ['guides/examples.md', 'Guides', 'Workflow Examples']