site_name: Factor.io Docs
site_url: http://docs.factor.io/
site_author: Factor.io
theme_dir: theme
repo_url: https://github.com/factor-io/docs/
pages:
- ['index.md', 'Getting Started']
- ['learn/step_1_before_you_start.md', 'Learn Factor.io', '1. Before you start']
- ['learn/step_2_your_first_command.md', 'Learn Factor.io', '2. Your first command']
- ['learn/step_3_your_first_workflow.md', 'Learn Factor.io', '3. Your first workflow']
- ['learn/step_4_getting_more_services.md', 'Learn Factor.io', '4. Getting more services']
- ['learn/step_5_auto_deploy.md', 'Learn Factor.io', '5. Automating deployments']
- ['learn/step_6_handling_failures.md', 'Learn Factor.io', '6. Handling failures']
- ['learn/step_7_organizing_workflows.md', 'Learn Factor.io', '7. Organizing workflows']
- ['learn/step_8_whats_next.md', 'Learn Factor.io', "8. What's Next?"]
- ['pro/overview.md', 'Factor.io Pro', 'Overview']
- ['pro/workflows.md', 'Factor.io Pro', 'Creating and running Workflows']
- ['pro/credentials.md', 'Factor.io Pro', 'Setting Credentials']
- ['pro/connectors.md', 'Factor.io Pro', 'Managing Connectors']
- ['pro/users.md', 'Factor.io Pro', 'Membership management']
- ['pro/jumpstarts.md', 'Factor.io Pro', 'Managing Jumpstarts']
- ['connectors/bitballoon.md', 'Connectors', 'Bitballoon']
- ['connectors/chef.md', 'Connectors', 'Chef']
- ['connectors/github.md', 'Connectors', 'Github']
- ['connectors/heroku.md', 'Connectors', 'Heroku']
- ['connectors/hipchat.md', 'Connectors', 'Hipchat']
- ['connectors/jenkins.md', 'Connectors', 'Jenkins']
- ['connectors/mailgun.md', 'Connectors', 'Mailgun']
- ['connectors/newrelic.md', 'Connectors', 'NewRelic']
- ['connectors/pagerduty.md', 'Connectors', 'PagerDuty']
- ['connectors/pushover.md', 'Connectors', 'Pushover']
- ['connectors/rackspace.md', 'Connectors', 'Rackspace']
- ['connectors/slack.md', 'Connectors', 'Slack']
- ['connectors/ssh.md', 'Connectors', 'SSH']
- ['connectors/timer.md', 'Connectors', 'Timer']
- ['connectors/travis.md', 'Connectors', 'Travis']
- ['connectors/trello.md', 'Connectors', 'Trello']
- ['connectors/tutum.md', 'Connectors', 'Tutum']
- ['connectors/web.md', 'Connectors', 'Web']
- ['guides/self_host.md', 'Guides', 'Self hosting']
- ['guides/build_custom_connectors.md', 'Guides', 'Build custom connectors']
- ['guides/workflows.md', 'Guides', 'Defining workflows']
- ['guides/examples.md', 'Guides', 'Workflow Examples']
- ['guides/running_connector_service.md', 'Guides', 'Running Connector Service']